package ca.destiny.evolution.creation.orc;

import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class RandomOrcNameGenerator {

    private static final List<String> males;
    private static final List<String> lastName;
    private static final List<String> females;

    static {
        males = Arrays.asList(
                "Abghat",
                "Durgash",
                "Trugagh",
                "Igubat",
                "Urim",
                "Hebub",
                "Gnarlug",
                "Guthakug",
                "Yar",
                "Urbul",
                "Lugrub",
                "Bat",
                "Jorgagu",
                "Yregh",
                "Opoguk",
                "Bidgug",
                "Bagamul",
                "Wakgut",
                "Gomatug",
                "Guarg",
                "Xunag",
                "Wegub",
                "Lum",
                "Grommok",
                "Omugug",
                "Umurn",
                "Gulm",
                "Lumdum",
                "Pughilug",
                "Dulphumph",
                "Oodagh",
                "Dalthu",
                "Sogorim",
                "Urulg",
                "Salthu",
                "Xurug",
                "Borgan",
                "Shulong",
                "Agugh",
                "Hig",
                "Sahgorim",
                "Alog",
                "Yroh",
                "Gubdagog",
                "Wrukaog",
                "Orakh",
                "Shagol",
                "Mazorn",
                "Somigig",
                "Rogan",
                "Lugrub",
                "Yambul",
                "Vlog",
                "Kertug",
                "Shulhug",
                "Slapdud",
                "Quomaugh",
                "Bazur",
                "Ogharod",
                "Vitgurat",
                "Nurghed",
                "Ginug",
                "Obghat",
                "Vrogak",
                "Apaugh",
                "Fagdud",
                "Sulmthu",
                "Xnath",
                "Bilge",
                "Pargu",
                "Brokil",
                "Jolagh",
                "Buomaugh",
                "Yolmar",
                "Zunodagh",
                "Dular",
                "Olumba",
                "Sildud",
                "Tulgan",
                "Uraugh",
                "Urul",
                "Urgran",
                "Vergu",
                "Ysagubar",
                "Krilge",
                "Urzog",
                "Zlog",
                "Sonagh",
                "Glush",
                "Golag",
                "Urul",
                "Urgran",
                "Vergu",
                "Ysagubar",
                "Krilge",
                "Urzog",
                "Zlog",
                "Sonagh",
                "Glush",
                "Golag",
                "Olumba",
                "Murkub",
                "Cabugbu",
                "Bandagh",
                "Gulrn",
                "Vakgu",
                "Frug",
                "Fozhug",
                "Mahk",
                "Vothug",
                "Sarhbub",
                "Wrukaog",
                "Abghat",
                "Sugorim",
                "Omegugh",
                "Oghuglat",
                "Yulakgh",
                "Vegum",
                "Hebub",
                "Rugbu");
        lastName = Arrays.asList("The Spear",
                "The Ruthless",
                "Shatterer",
                "Pride Bruiser",
                "Giant Trasher",
                "The Putrid",
                "Storm Killer",
                "Poison Marauder",
                "Brass Hammer",
                "Nose Gouger",
                "Storm Slicer",
                "Teeth Strangler",
                "Flesh Strangler",
                "The Grave",
                "Brain Heel",
                "The Cutter",
                "Nose Smasher",
                "Venom Queller",
                "The Fearless",
                "Beast Butcher",
                "The Smug",
                "The Wrathful",
                "Death Cutter",
                "The Vivid",
                "Iron Squasher",
                "Rib Flayer",
                "Gnome Spear",
                "The Crazy",
                "The Violent",
                "Fiend Cracker",
                "The Prime",
                "The Crooked",
                "The Infernal",
                "The Disfigured",
                "Slave Wrecker",
                "The Putrid",
                "The Fierce",
                "The Cold",
                "Elf Squasher",
                "The Enormous",
                "Smoke Cruncher",
                "The Outlandish",
                "Scale Cleaver",
                "The Wild",
                "Blood Quasher",
                "Spite Mutilator",
                "Doom Sword",
                "Steel Mutilator",
                "Eye Gouger",
                "Iron Mutilator",
                "Throat Splitter",
                "The Ugly",
                "The Volatile",
                "The Fierce",
                "Brain Masher",
                "Vein Slicer",
                "Death Scalper",
                "The Broad",
                "The Colossal",
                "The Barbarian",
                "Pest Razer",
                "Dream Cleaver",
                "Feet Reaper",
                "Ghost Crusher",
                "The Barbarian",
                "Ash Pummel",
                "Thunder Strangler",
                "The Brutal",
                "The Maniac",
                "The Colossal",
                "Ankle Masher",
                "The Ugly",
                "The Infernal"
        );
        females = Arrays.asList(
                "Durz",
                "Grat",
                "Mog",
                "Urog",
                "Bogdub",
                "Murbol",
                "Snak",
                "Shadbak",
                "Bulak",
                "Bolar",
                "Bor",
                "Arob",
                "Rolfish",
                "Lagakh",
                "Glob",
                "Ghob",
                "Ghak",
                "Rogbut",
                "Atub",
                "Ugor",
                "Shadbak",
                "Garakh",
                "Bulfim",
                "Gluronk",
                "Shazgob",
                "Rogmesh",
                "Ulumpha",
                "Ulumpha",
                "Urog",
                "Shadbak",
                "Badbog",
                "Urog",
                "Borba",
                "Rogbut",
                "Gulfim",
                "Lagakh",
                "Grat",
                "Snak",
                "Grazob",
                "Gul",
                "Rolfish",
                "Bashuk",
                "Glasha",
                "Burzob",
                "Bagrak",
                "Lagakh",
                "Ushat",
                "Murbol",
                "Shadbak",
                "Burzob",
                "Durz",
                "Lambug",
                "Ulumpha",
                "Lambug",
                "Bulfim",
                "Gulfim",
                "Badbog",
                "Lambug",
                "Shagdub",
                "Lash",
                "Shagdub",
                "Shagdub",
                "Grazob",
                "Atub",
                "Gulfim",
                "Batul",
                "Atub",
                "Nargol",
                "Ghak",
                "Rolfish",
                "Shazgob",
                "Ugor",
                "Murzush",
                "Shadbak",
                "Uloth",
                "Rulfim",
                "Ushat",
                "Bugdurash",
                "Murob",
                "Ushug");
    }

    public static String getMaleFirstName() {
        return males.get(getRandomNumberInts(0, males.size() - 1));
    }

    public static String getLastName() {
        return lastName.get(getRandomNumberInts(0, lastName.size() - 1));
    }

    public static String getFemaleFirstName() {
        return females.get(getRandomNumberInts(0, females.size() - 1));
    }

    public static int getRandomNumberInts(int min, int max) {
        Random random = new Random();
        return random.ints(min, (max + 1)).findFirst().orElse(0);
    }
}
